server:
  port: 9091
spring:
  application:
    name: university_portal
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://service-postgres-db:5432/student_db
    username: postgres
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
